# -*- coding: utf-8 -*-
"""ABC-анализ_продаж_аптека.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psTIp1I_JsoX_JxrxavjhXXahMZ6Oyyv
"""

import pandas as pd
import numpy as np
df=pd.read_csv('data.csv',encoding='1251', delimiter=',')
pd.set_option('display.max_columns',25)
pd.set_option('display.float_format','{:.2f}'.format)

# Функция для расчета ABC-анализа для данных с датафреймом pandas
def perform_abc(df,index):
  cols=list(df.columns)  # Список столбцов датафрейма (количество, розничная сумма продаж)
  cols.remove(index) # Убираем индекс - остаются столбцы для расчета (количество, розничная сумма продаж)
  # Группировка по индексу с подсчетом суммы даннных столбцов для анализа (общей суммы количества, общей суммы розничной суммы продаж)
  groupped_df=df.groupby(index).agg({col: 'sum' for col in cols})
  for col in cols:
    # Подсчет среднего значения значений столбца (сумма/общую сумму) и сортировка по убыванию
    groupped_df[f'real_{col}']=groupped_df[col]/groupped_df[col].sum()
    groupped_df=groupped_df.sort_values(f'real_{col}',ascending=False)
    # Подсчет куммулятивной суммы среднего значения столбца - вклад накопительным итогом
    groupped_df[f'cumsum_{col}']=groupped_df[f'real_{col}'].cumsum()
    # Определение группы ABC
    groupped_df[f'ABC_{col}']=np.where(groupped_df[f'cumsum_{col}']<0.8,'A',np.where(groupped_df[f'cumsum_{col}']<0.95,'B','C'))
  return groupped_df[cols+[f'ABC_{col}' for col in cols]]

df1=df[['DR_NDrugs','DR_Kol','DR_CRoz']]
perform_abc(df1,index='DR_NDrugs')